[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/'
]

optimizer = true
optimizer_runs = 2_000_000

[fmt]
line_length = 150
tab_width = 4
bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
polygon="https://polygon.rpc.thirdweb.com"
scroll="scroll.rpc.thirdweb.com"

scroll_sepolia="scroll-sepolia-testnet.rpc.thirdweb.com"